### ISSUE TITLE
Some tests fail when dealing with pulseaudio

### ISSUE THREAD

**Issue by khurshid-alam** [AyatanaIndicators/ayatana-indicator-sound#1]
Integration tests are failing against pulseaudio 1.11. It seems it can't find pluseaudio on the bus. startPulseDesktop() is failing and throwing exception.

**Comment by tari01** [comment]
@khurshid-alam I have changed the title to a more generic one, I hope you don't mind.

@sunweaver I have been building dissecting, testing and rebuilding the past two days, and I am now at a point of giving up (i.e. Help Wanted).

3 tests fail:
- volume-control-test
- notifications-test
- indicator-test

When libdbustest's DbusTestService is created in a C++ GTest code, any later C code wanting to create a DBusConnection to pulseadio fails with

`volume-control-pulse.vala:742: unable to get pulse unix socket: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.PulseAudio1 was not provided by any .service files`

After that we get some nice segfaults in places where they definitely should not happen. This appears to be some major malfunction in libdbustest, combined with some possible leaks in Vala.

**Comment by tari01** [comment]
@khurshid-alam:

I have just checked to see if we still have any failing tests, but the build seems fine. There have been so many commits touching the tests (over the years) that I cannot find the exact one that fixed the issue. I am closing this as solved now, but feel free to file a new issue in case you run into problems.
