### ISSUE TITLE
Ubuntu 20.10: Unable to connect to dbus server at 'unix:path=/run/user/1000/pulse/dbus-socket'

### ISSUE THREAD

**Issue by colourful-land** [AyatanaIndicators/ayatana-indicator-sound#15]
Background: I'm having a problem with Ubuntu's sound indicator so installed this one to try.

There is no README or instruction on how to launch the indicator. 

I locked at package content and there is only one executable `/usr/libexec/ayatana-indicator-sound/ayatana-indicator-sound-service` so it must be.

But it gives this:
````
(process:33028): ayatana-indicator-sound-WARNING **: 16:55:00.949: volume-control-pulse.vala:745: Unable to connect to dbus server at 'unix:path=/run/user/1000/pulse/dbus-socket': No se pudo conectar: No existe el archivo o el directorio
````
And there is no new icons appearing on the upper-right corner.

**Comment by tari01** [comment]
@colourful-land Can you please tell us which Desktop Environment you are using?

**Comment by tari01** [comment]
Just a thought: Could it be that Ubuntu runs PulseAudio without DBus support?!

Please check your **/etc/pulse/default.pa** and look for **load-module module-dbus-protocol**. If it's there, but commented out - uncomment it. If it's not in the file, just add it to the end on a new line.

The best would be to reboot now, to see if the indiacator starts automagically, but you can also restart pulseaudio with `pulseaudio -k` and manually test the indicator again.

**Comment by tari01** [comment]
This seems to be an Ubuntu issue, not Ayatana, closing.
