### ISSUE TITLE
Integration tests are failing due to gicon regression in glib >= 2.58

### ISSUE THREAD

**Issue by khurshid-alam** [AyatanaIndicators/ayatana-indicator-sound#2]
Integration tests are failing due to gicon regression in glib >= 2.58
This is same bug as Ubuntu's indicator-sound.

See https://bugs.launchpad.net/ubuntu/+source/indicator-sound/+bug/1795888

**Comment by khurshid-alam** [comment]
@sunweaver ?

**Comment by sunweaver** [comment]
Can you possibly file a pull request?
Mike

On Friday, October 12, 2018, Khurshid Alam wrote:
> @sunweaver ?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/AyatanaIndicators/ayatana-indicator-sound/issues/2#issuecomment-42931008

-- 
Sent from my Fairphone (powered by SailfishOS)

**Comment by tari01** [comment]
I am closing this, since it is no longer a problem. The other issue still very much is.

**Comment by sunweaver** [comment]
HI Robert,

On  Do 11 Mär 2021 15:26:16 CET, Robert Tari wrote:

> I am closing this, since it is no longer a problem. The other issue  
> still very much is.

waht commit resolved this issue? Or a just-vanished-type-of-error?

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler Str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: ***@***.***, http://das-netzwerkteam.de

**Comment by tari01** [comment]
> waht commit resolved this issue? Or a just-vanished-type-of-error?

It's the vanishing type. I'll post some details on #1, that one is a mess.
