### ISSUE TITLE
ayatana-indicator-sound misses playback control (Previous, Play, Next) buttons

### ISSUE THREAD

**Issue by N0rbert** [AyatanaIndicators/ayatana-indicator-sound#28]
Steps to reproduce:
1. Install any Ubuntu MATE version which ships ayatana-indicator-sound - 20.10, 21.04 or upcoming 21.10
2. Launch preinstalled Rhythmbox player, select any internet Radio station to play
3. Open ayatana-indicator-sound by clicking on volume button

Expected results:
* ayatana-indicator-sound shows the following interface elements - *artist*, *song name*, Previous, Play, Next control buttons as it shown on screenshot below from Ubuntu MATE 20.04 LTS:
    
    > ![focal](https://user-images.githubusercontent.com/309456/130291599-92e5ff43-2d4c-4b6f-b159-1cced32e7bd9.png)

Actual results:
* ayatana-indicator-sound shows only *artist* and *song name* as shown on screenshot below from Ubuntu MATE 20.10:

    > ![groovy](https://user-images.githubusercontent.com/309456/130291912-a53ea7a8-314d-45f2-8ce0-bb02556f7715.png)

Note: the same happens in the latest Ubuntu MATE 21.10 (development branch). Downstream bug report - https://pad.lv/1940716 .

**Comment by tari01** [comment]
@N0rbert 

I have tested a source build with Ubuntu MATE 21.04 and the controls are there. This is a packaging bug, so closing.

@sunweaver 

Perhaps a new release is due into Debian?
