### ISSUE TITLE
Redundant "Volume" menu item + testing option

### ISSUE THREAD

**Issue by tari01** [AyatanaIndicators/ayatana-indicator-sound#3]
It builds, integrates and works beautifully in Arch + MATE. However, there is a "Volume" menu item that does not do anything.

I have also attached a patch that adds a testing option, so it builds without tweaks:

```
cd ${pkgname}
patch -Np1 -i ../0001.add-testing-option.patch
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBEXECDIR=lib -DCMAKE_INSTALL_LOCALSTATEDIR=/var -Denable_tests=OFF
make DESTDIR=${pkgdir} install
```

[0001.add-testing-option.patch.zip](https://github.com/AyatanaIndicators/ayatana-indicator-sound/files/2946710/0001.add-testing-option.patch.zip)

**Comment by khurshid-alam** [comment]
Does it compile against glib > 2.58.2 ? Remember all tests must pass. At the moment there are gicon regression (see #2) but even with the fix for gicon,  then mic out test fails (which is weird because mic-in test passes).

**Comment by tari01** [comment]
@khurshid-alam 

I have GLib 2.58.3 - with that one it builds. Note, however, that my patch ads an option to DISABLE the tests in CMake with -Denable_tests=OFF.

The code we have right now has hardcoded testing enabled, which makes the package depend on all sorts of exotic libraries not really available in Non-Buntu.

**Comment by khurshid-alam** [comment]
That's odd. I am compiling on Ubuntu 19.04, only ubuntu specific library is libunity-dev. But in debian/control, it has halo package so that it can be compiled without it. 

**Against Glib > 2.58.x**

1) Integration tests fails
2) With [gicon fix ](https://git.launchpad.net/~khurshid-alam/indicator-sound/+git/ayatana-indicator-sound/commit/?id=ca29c367ca7f3a6dbcb459ab8740fa34fe9d7e0d) it compiles but only external micslider test fails. 

**Against Glib > 2.60.x**

There are lots of errors
1) **gicon fix doesn't work anymore !** though it still works for indicator sound.

2) I get error like
```
ActUserManager: user (null) has no username (object path: /org/freedesktop/Accounts/UserTest, uid: 0)
```
which seems coming from qgetenv("USER"). May be it requires another approach to set user for test environment

3) 
```
volume-control-pulse.vala:745: Unable to connect to dbus server at 'unix:path=/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/tests/test-home/.config/pulse/dbus-socket': Could not connect: No such file or directory
```
This seems related to (2). So when 2 get fixed 3 will get fixed as well.

See full build log here: https://launchpadlibrarian.net/416093469/buildlog_ubuntu-disco-amd64.indicator-sound_12.10.2+18.10.20180612-0ubuntu1+201903220811~ubuntu19.04.1_BUILDING.txt.gz

**Comment by sunweaver** [comment]
Hi Khurshid,

On  Fr 22 Mär 2019 17:49:59 CET, Khurshid Alam wrote:

> That's odd. I am compiling on Ubuntu 19.04, only ubuntu specific  
> library is libunity-dev. But in debian/control, it has halo package  
> so that it can be compiled without it.
>
> **Against Glib > 2.58.x**
>
> 1) Integration tests fails
> 2) With [gicon fix  
> ](https://git.launchpad.net/~khurshid-alam/indicator-sound/+git/ayatana-indicator-sound/commit/?id=ca29c367ca7f3a6dbcb459ab8740fa34fe9d7e0d) it compiles but only external micslider test  
> fails.
>
> **Against Glib > 2.60.x**
>
> There are lots of errors
> 1) **gicon fix doesn't work anymore !** though it still works for  
> indicator sound.
>
> 2) I get error like
> ```
> ActUserManager: user (null) has no username (object path:  
> /org/freedesktop/Accounts/UserTest, uid: 0)
> ```
> which seems coming from qgetenv("USER"). May be it requires another  
> approach to set user for test environment
>
> 3)
> ```
> volume-control-pulse.vala:745: Unable to connect to dbus server at  
> 'unix:path=/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/tests/test-home/.config/pulse/dbus-socket': Could not connect: No such file or  
> directory
> ```
> This seems related to (2). So when 2 get fixed 3 will get fixed as well.
>
> See full build log here:  
> https://launchpadlibrarian.net/416093469/buildlog_ubuntu-disco-amd64.indicator-sound_12.10.2+18.10.20180612-0ubuntu1+201903220811~ubuntu19.04.1_BUILDING.txt.gz

please don't mix up ayatana-indicator-sound and indicator-sound. The  
indicator-sound is the original project by Canonical, not so much  
maintained anymore and Ubuntu-specific in its code base. The  
ayatana-indicator-sound is meant to be cross-distro supportive, but  
not yet ready for all distros. Note that other system Ayatnana  
Indicators are more advanced. The sound indicator and the keyboard  
indicator (in Ayatana Indicators) need love.

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
Hi Robert,

On  Fr 22 Mär 2019 12:00:05 CET, Robert Tari wrote:

> @khurshid-alam
>
> I have GLib 2.58.3 - with that one it builds. Note, however, that my  
> patch ads an option to DISABLE the tests in CMake with  
> -Denable_tests=OFF.
>
> The code we have right now has hardcoded testing enabled, which  
> makes the package depend on all sorts of exotic libraries not really  
> available in Non-Buntu.

Please make sure I have PRs for patches to be merged. Thanks.

I will have more time for Ayatana Indicators starting in April.

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by khurshid-alam** [comment]
@sunweaver 
>please don't mix up ayatana-indicator-sound and indicator-sound. The
indicator-sound is the original project by Canonical, not so much
maintained anymore and Ubuntu-specific in its code base. 

Hi Mike,

I am not mixing up at all. In Ubuntu 19.04 there is FTBFS for ayatana-indicator-sound. Does it compile in sid ? I will propose a merge if I find a way to fix those tests. Also it requires fix against vala >= 44

**Comment by sunweaver** [comment]
Hi,

On Friday, 22 March 2019, Khurshid Alam wrote:
> @sunweaver 
> >please don't mix up ayatana-indicator-sound and indicator-sound. The
> indicator-sound is the original project by Canonical, not so much
> maintained anymore and Ubuntu-specific in its code base. 
> 
> Hi Mike,
> 
> I am not mixing up at all. In Ubuntu 19.04 there is FTBFS for ayatana-indicator-sound. Does it compile in sid ? I will propose a merge if I find a way to fix those tests. Also it requires fix against vala >= 44
> 

Ah,ok. Cool. Help on the Ubuntu FTBFS will be much appreciated.

To make the sound indicator usable cross-distro, we have to make the ubuntu sound schema available cross distro ( under the name ayatana-sounds, maybe?).

Also, there was some issue about accountsservice integration, iirc.

Builds on Debian sid work, as they omit parts of the code/build path.

See https://jenkins.arctica-project.org/ for some build logs against Debian and Ubuntu. The nightly builds do build when somethings gets pushed to master.

Thanks for chiming in!!! Looking forward to your contribs.

Mike
-- 
Sent from my Sailfish device

**Comment by zippy-zebu** [comment]
Same here, volume menu doesn't do anything. 

And also it doesn't compile with latest glib. (Sid still has 2.58.3)

**Comment by sunweaver** [comment]
On  So 21 Jul 2019 08:51:04 CEST, zippy-zebu wrote:

> Same here, volume menu doesn't do anything.
>
> And also it doesn't compile with latest glib. (Sid still has 2.58.3)

Thanks. Noted. I hope to be able to "get back to" Ayatana Indicators  
hacking over the second half of the year. Too many other projects  
demanding my attention with prio at the moment.

PRs are always welcome...

Please note that the sound indicator in Ayatana Indicators really  
needs more love and attention, esp. regarding its portability to  
non-Ubuntu based distros.

Greets,
Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by tari01** [comment]
I am closing this because the problem is really in **ayatana-ido** not being able to build custom **GMenu** items.
