### ISSUE TITLE
Make it available on Ubuntu ?

### ISSUE THREAD

**Issue by zippy-zebu** [AyatanaIndicators/ayatana-indicator-sound#5]
Unlike other ayatana indicators, this isn't available for Ubuntu (19.04 & 20.04). I would really like to use it with ubuntu-mate.

Please make it available on Ubuntu or at least provide a deb in release.

Thanks.

**Comment by khurshid-alam** [comment]
@sunweaver

**Comment by sunweaver** [comment]
@zippy-zebu: the -sound Ayatana System Indicator will be available in Ubuntu 20.10.
