### ISSUE TITLE
FTBFS on focal (due to missing liblomiri-api-dev)

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-indicator-sound#59]
@tari01 The current main branch fails to CI-build, because gmenuharness needs lomiri-api as a build-dependency. This all fails on Travis CI for Ubuntu 20.04 currently.

Two strategies:

  1. Don't build/run the gmenuharness based tests during builds/tests on focal
  2. Also build lomiri-api from source before building gmenuharness for CI builds 

Opinions?

**Comment by tari01** [comment]
> @tari01 The current main branch fails to CI-build, because gmenuharness needs lomiri-api as a build-dependency. This all fails on Travis CI for Ubuntu 20.04 currently.
> 
> Two strategies:
> 
>     1. Don't build/run the gmenuharness based tests during builds/tests on focal
> 
>     2. Also build lomiri-api from source before building gmenuharness for CI builds
> 
> 
> Opinions?

We added Ubuntu builds only because the Ubuntu-specific dependencies. Since we don't use those anymore, I think it's safe to skip testing on Ubuntu and rely on the Debian results. I would eventually go further and drop Ubuntu builds entirely (they will only become a CI overhead).

**Comment by sunweaver** [comment]
Well, I'd like to be prepared for Ubuntu 20.04 breakages when Ayatana Indicators get pulled over to Ubuntu Touch 20.04. This is my main reason for doing the Ubuntu 20.04 CI builds. So, in this respect, we'd rather should continue with having them around. Don't you think?

**Comment by tari01** [comment]
> Well, I'd like to be prepared for Ubuntu 20.04 breakages when Ayatana Indicators get pulled over to Ubuntu Touch 20.04. This is my main reason for doing the Ubuntu 20.04 CI builds. So, in this respect, we'd rather should continue with having them around. Don't you think?

Definitely keep Ubuntu during the transition. I would conditionally build gmenuharness for Debian only, though.
