### ISSUE TITLE
Prefer symbolic icon for volume

### ISSUE THREAD

**Issue by newhoa** [AyatanaIndicators/ayatana-indicator-sound#79]
Currently ayatana-indicator-sound prefers non-symbolic icons. So if an icon theme has `audio-volume-low-symbolic` in its `symbolic` folder and `audio-volume-low` in its `48/status` folder, it will choose the 48px non-symbolic icon.

Panels can be light or dark and preferring a symbolic icon would be more compatible with many themes and be much clearer and more legible with any style.

[Here](https://github.com/AyatanaIndicators/ayatana-indicator-sound/blob/main/src/service.vala#L311-L321) and [here](https://github.com/AyatanaIndicators/ayatana-indicator-sound/blob/6642ace1c37b21a21d086f1796c9da2594c6f62b/tests/integration/test-indicator.cpp#L75-L98) look like relevant spots where this might need to be addressed. I'm not familiar with the code so I'm not sure if changing the names would be enough or if more would need to be added (like if using non-symbolic as fallbacks or limiting the maximum size).

**Comment by tari01** [comment]
It is up to the theme to provide icons that control what Ayatana system indicators present to the user. These icons should always end with `-panel`.

For example, this is the search order for the **audio-volume-low** icon:

1. audio-volume-low-panel-symbolic
2. audio-volume-low-panel
3. audio-volume-low
4. audio-volume
5. audio

The first full match will be the icon that you see (as an alternative,  **audio-volume-low-panel-symbolic** can be a symlink to **audio-volume-low-panel**). I'm closing this as already implemented.
